In [1]:
import pandas as pd
import numpy as np
import time

In [2]:
df_stop_101 = pd.read_csv('stopDataByStation/station101Mar7toMar15.csv')
df_stop_102 = pd.read_csv('stopDataByStation/station102Mar7toMar15.csv')
df_stop_103 = pd.read_csv('stopDataByStation/station102Mar7toMar15.csv')
df_sensor = pd.read_csv('sensorDataMar8toMar20.csv')

In [3]:
df_stop_101['Starttid'] = df_stop_101['Starttid'].astype('datetime64')
df_stop_101['Sluttid'] = df_stop_101['Sluttid'].astype('datetime64')
df_stop_102['Starttid'] = df_stop_102['Starttid'].astype('datetime64')
df_stop_102['Sluttid'] = df_stop_102['Sluttid'].astype('datetime64')
df_stop_103['Starttid'] = df_stop_103['Starttid'].astype('datetime64')
df_stop_103['Sluttid'] = df_stop_103['Sluttid'].astype('datetime64')
df_sensor['time'] = df_sensor['time'].astype('datetime64')

In [4]:
df_stop_101.isnull().sum()

Unnamed: 0         0
Mätpunkt           0
Ordernummer        0
Artikel            0
Artikelnummer      0
Artikeltyp         0
Skift              0
Starttid           0
Minuter            0
Sluttid            0
Total stopptid     0
Stopporsak         0
Station            0
Kommentar         81
dtype: int64

In [6]:
df_stop_103.head()

,Unnamed: 0,Mätpunkt,Ordernummer,Artikel,Artikelnummer,Artikeltyp,Skift,Starttid,Minuter,Sluttid,Total stopptid,Stopporsak,Station,Kommentar
0,209,P4,271143,MINIR FILT 15CM GAV GR� LAGR TRANSP,454515052,Roller,Eftermiddag,2023-03-15 16:13:44.533,2.878333,2023-03-15 16:16:37.262,00:02:52.700000,Mekaniskt fel,102. Avskjutning rullar,NaN
1,210,P4,271143,MINIR FILT 15CM GAV GR� LAGR TRANSP,454515052,Roller,Eftermiddag,2023-03-15 16:05:00.481,1.576667,2023-03-15 16:06:35.082,00:01:34.600000,Mekaniskt fel,102. Avskjutning rullar,NaN
2,211,P4,271143,MINIR FILT 15CM GAV GR� LAGR TRANSP,454515052,Roller,Eftermiddag,2023-03-15 15:49:47.641,1.436667,2023-03-15 15:51:13.818,00:01:26.200000,Mekaniskt fel,102. Avskjutning rullar,NaN
3,212,P4,271143,MINIR FILT 15CM GAV GR� LAGR TRANSP,454515052,Roller,Eftermiddag,2023-03-15 15:45:01.101,1.398333,2023-03-15 15:46:24.960,00:01:23.900000,Mekaniskt fel,102. Avskjutning rullar,NaN
4,213,P4,271143,MINIR FILT 15CM GAV GR� LAGR TRANSP,454515052,Roller,Eftermiddag,2023-03-15 15:39:52.701,1.780000,2023-03-15 15:41:39.546,00:01:46.800000,Mekaniskt fel,102. Avskjutning rullar,NaN

In [7]:
df_sensor.head()

,Unnamed: 0,time,humi_s101,humi_s1021,humi_s1022,humi_s103,press_s101,press_s1021,press_s1022,press_s103,temp_s101,temp_s1021,temp_s1022,temp_s103
0,0,2023-03-10 18:16:13,21474836.47,0.00,0.00,41.28,2102.78,0.00,0.00,3453.57,21474836.47,0.00,0.0,19.54
1,1,2023-03-14 11:11:02,21474836.47,21474836.47,19.13,0.00,3474.52,3600.55,3431.85,0.00,21474836.47,21474836.47,33.6,0.00
2,2,2023-03-14 11:45:31,21474836.47,21474836.47,19.13,0.00,3474.52,3600.55,3431.85,0.00,21474836.47,21474836.47,33.6,0.00
3,3,2023-03-14 11:46:15,21474836.47,21474836.47,19.13,0.00,3474.52,3600.55,3431.85,0.00,21474836.47,21474836.47,33.6,0.00
4,4,2023-03-14 11:46:58,21474836.47,21474836.47,19.13,0.00,3474.52,3600.55,3431.85,0.00,21474836.47,21474836.47,33.6,0.00

In [8]:
df_stop_103.dtypes

Unnamed: 0                 int64
Mätpunkt                  object
Ordernummer                int64
Artikel                   object
Artikelnummer              int64
Artikeltyp                object
Skift                     object
Starttid          datetime64[ns]
Minuter                  float64
Sluttid           datetime64[ns]
Total stopptid            object
Stopporsak                object
Station                   object
Kommentar                float64
dtype: object

In [9]:
df_stop_101['time'] = df_stop_101.Starttid
df_stop_102['time'] = df_stop_102.Starttid
df_stop_103['time'] = df_stop_103.Starttid

In [10]:
df_stop_101

,Unnamed: 0,Mätpunkt,Ordernummer,Artikel,Artikelnummer,Artikeltyp,Skift,Starttid,Minuter,Sluttid,Total stopptid,Stopporsak,Station,Kommentar,time
0,0,P4,272085,MINIR MICMEX 15CM GAV GR� LAGR TRANSP,584516052,Roller,Eftermiddag,2023-03-09 19:25:24.531,253.358333,2023-03-09 23:38:46.023,04:13:21.500000,Mekaniskt fel,101. Avskärning väv,NaN,2023-03-09 19:25:24.531
1,1,P4,272083,MINIR FILT 5CM GAV GR� LAGR TRANSP KORT,454505009,Roller,Eftermiddag,2023-03-07 20:47:50.003,5.535000,2023-03-07 20:53:22.153,00:05:32.100000,Mekaniskt fel,101. Avskärning väv,NaN,2023-03-07 20:47:50.003
2,18,P4,271143,MINIR FILT 15CM GAV GR� LAGR TRANSP,454515052,Roller,Eftermiddag,2023-03-15 20:40:45.221,1.283333,2023-03-15 20:42:02.222,00:01:17,Mekaniskt fel,101. Avskärningskniv,NaN,2023-03-15 20:40:45.221
3,19,P4,271143,MINIR FILT 15CM GAV GR� LAGR TRANSP,454515052,Roller,Eftermiddag,2023-03-15 20:13:21.802,1.441667,2023-03-15 20:14:48.295,00:01:26.500000,Mekaniskt fel,101. Avskärningskniv,NaN,2023-03-15 20:13:21.802
4,20,P4,271143,MINIR FILT 15CM GAV GR� LAGR TRANSP,454515052,Roller,Eftermiddag,2023-03-15 19:25:53.382,2.243333,2023-03-15 19:28:07.965,00:02:14.600000,Mekaniskt fel,101. Avskärningskniv,NaN,2023-03-15 19:25:53.382
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,202,P4,272098,MINIRULLE ANTEX 5CM GAV GR� LAGR VIT,584505000,Roller,Eftermiddag,2023-03-08 20:37:29.201,2.440000,2023-03-08 20:39:55.560,00:02:26.400000,Mekaniskt fel,101. Utmatningsband,NaN,2023-03-08 20:37:29.201
77,203,P4,272098,MINIRULLE ANTEX 5CM GAV GR� LAGR VIT,584505000,Roller,Eftermiddag,2023-03-08 20:31:54.861,3.020000,2023-03-08 20:34:56.068,00:03:01.200000,Mekaniskt fel,101. Utmatningsband,NaN,2023-03-08 20:31:54.861
78,204,P4,272098,MINIRULLE ANTEX 5CM GAV GR� LAGR VIT,584505000,Roller,Eftermiddag,2023-03-08 20:23:45.481,1.246667,2023-03-08 20:25:00.315,00:01:14.800000,Mekaniskt fel,101. Utmatningsband,NaN,2023-03-08 20:23:45.481
79,205,P4,272084,MINIRULLE ANTEX 5CM GAV GR� LAGR VIT,584505000,Roller,Eftermiddag,2023-03-08 16:16:57.144,1.531667,2023-03-08 16:18:29.043,00:01:31.900000,Mekaniskt fel,101. Utmatningsband,NaN,2023-03-08 16:16:57.144
80,207,P4,272297,MINIR 15 CM GAV GR� LAGR TRANSP,424515083,Roller,Förmiddag,2023-03-14 07:13:45.220,3.788333,2023-03-14 07:17:32.558,00:03:47.300000,Mekaniskt fel,101. Vävvagn,NaN,2023-03-14 07:13:45.220

In [11]:
df_sensor_stop101 =  pd.concat([df_sensor, df_stop_101], axis=0, ignore_index=True).sort_values(by='time').reset_index().drop(['index','Unnamed: 0'], axis=1)
df_sensor_stop102 =  pd.concat([df_sensor, df_stop_102], axis=0, ignore_index=True).sort_values(by='time').reset_index().drop(['index','Unnamed: 0'], axis=1)
df_sensor_stop103 =  pd.concat([df_sensor, df_stop_103], axis=0, ignore_index=True).sort_values(by='time').reset_index().drop(['index','Unnamed: 0'], axis=1)

# Annotation

In [349]:
errors = df_stop_101.Stopporsak.unique()
errors

array(['Mekaniskt fel', 'Reparatör på plats'], dtype=object)

In [350]:
df_stop_101['Stopporsak'].value_counts()

Mekaniskt fel         44
Reparatör på plats    37
Name: Stopporsak, dtype: int64

In [16]:
# Create a new column indicating whether an error occurred at each timestamp
errors = df_stop_101.Stopporsak.unique()
def error_indicator(row):
    if row['Stopporsak'] in errors:
        return 1
    else:
        return 0

df_sensor_stop101['error_indicator'] = df_sensor_stop101.apply(error_indicator, axis=1)
df_sensor_stop102['error_indicator'] = df_sensor_stop102.apply(error_indicator, axis=1)
df_sensor_stop103['error_indicator'] = df_sensor_stop103.apply(error_indicator, axis=1)

# Calculate the remaining useful life for each timestamp
def calculate_RUL(df):
    RUL = np.zeros(len(df))
    last_error_index = -1
    for i, row in df.iterrows():
        if row['error_indicator'] == 1:
            last_error_index = i
        if last_error_index == -1:
            RUL[i] = np.nan
        else:
            RUL[i] = (row['time'] - df.loc[last_error_index]['time'] ).total_seconds()
    return RUL

df_sensor_stop101['RUL'] = calculate_RUL(df_sensor_stop101)
df_sensor_stop102['RUL'] = calculate_RUL(df_sensor_stop102)
df_sensor_stop103['RUL'] = calculate_RUL(df_sensor_stop103)

In [17]:
df_sensor_stop102

,time,humi_s101,humi_s1021,humi_s1022,humi_s103,press_s101,press_s1021,press_s1022,press_s103,temp_s101,...,Skift,Starttid,Minuter,Sluttid,Total stopptid,Stopporsak,Station,Kommentar,error_indicator,RUL
0,2023-03-07 06:13:08.522000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Förmiddag,2023-03-07 06:13:08.522,1.575000,2023-03-07 06:14:42.990,00:01:34.500000,Mekaniskt fel,102. Avskjutning rullar,NaN,1,0.000000
1,2023-03-07 06:46:06.361000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Förmiddag,2023-03-07 06:46:06.361,2.790000,2023-03-07 06:48:53.722,00:02:47.400000,Mekaniskt fel,102. Avskjutning rullar,NaN,1,0.000000
2,2023-03-07 07:08:33.542000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Förmiddag,2023-03-07 07:08:33.542,2.445000,2023-03-07 07:11:00.222,00:02:26.700000,Mekaniskt fel,102. Avskjutning rullar,NaN,1,0.000000
3,2023-03-07 07:12:28.701000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Förmiddag,2023-03-07 07:12:28.701,1.201667,2023-03-07 07:13:40.761,00:01:12.100000,Mekaniskt fel,102. Avskjutning rullar,NaN,1,0.000000
4,2023-03-07 07:15:33.262000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Förmiddag,2023-03-07 07:15:33.262,1.930000,2023-03-07 07:17:29.042,00:01:55.800000,Mekaniskt fel,102. Avskjutning rullar,NaN,1,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11994,2023-03-20 06:12:36.003978,21474836.47,42.65,0.0,0.0,3230.97,3474.43,0.0,0.0,21474836.47,...,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,0,385401.041978
11995,2023-03-20 06:13:17.054457,21474836.47,42.65,0.0,0.0,3230.97,3474.43,0.0,0.0,21474836.47,...,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,0,385442.092457
11996,2023-03-20 06:13:58.123391,21474836.47,42.65,0.0,0.0,3230.97,3474.43,0.0,0.0,21474836.47,...,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,0,385483.161391
11997,2023-03-20 06:14:39.179122,21474836.47,42.65,0.0,0.0,3230.97,3474.43,0.0,0.0,21474836.47,...,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,0,385524.217122
11998,2023-03-20 06:15:20.245297,21474836.47,42.65,0.0,0.0,3230.97,3474.43,0.0,0.0,21474836.47,...,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,0,385565.283297

# Try2

In [18]:
df_sensor_stop101

,time,humi_s101,humi_s1021,humi_s1022,humi_s103,press_s101,press_s1021,press_s1022,press_s103,temp_s101,...,Skift,Starttid,Minuter,Sluttid,Total stopptid,Stopporsak,Station,Kommentar,error_indicator,RUL
0,2023-03-07 04:20:57.861000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Natt,2023-03-07 04:20:57.861,1.343333,2023-03-07 04:22:18.437,00:01:20.600000,Mekaniskt fel,101. Matning vävmagasin,NaN,1,0.000000
1,2023-03-07 05:28:49.282000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Natt,2023-03-07 05:28:49.282,1.948333,2023-03-07 05:30:46.141,00:01:56.900000,Mekaniskt fel,101. Rör utan väv,NaN,1,0.000000
2,2023-03-07 07:24:01.062000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Förmiddag,2023-03-07 07:24:01.062,1.716667,2023-03-07 07:25:44.042,00:01:43,Mekaniskt fel,101. Drivning påläggningsdorn,NaN,1,0.000000
3,2023-03-07 07:55:22.541000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Förmiddag,2023-03-07 07:55:22.541,2.020000,2023-03-07 07:57:23.701,00:02:01.200000,Mekaniskt fel,101. Drivning påläggningsdorn,NaN,1,0.000000
4,2023-03-07 08:15:18.802000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Förmiddag,2023-03-07 08:15:18.802,1.355000,2023-03-07 08:16:40.064,00:01:21.300000,Reparatör på plats,101. Drivning påläggningsdorn,NaN,1,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11998,2023-03-20 06:12:36.003978,21474836.47,42.65,0.0,0.0,3230.97,3474.43,0.0,0.0,21474836.47,...,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,0,376299.821978
11999,2023-03-20 06:13:17.054457,21474836.47,42.65,0.0,0.0,3230.97,3474.43,0.0,0.0,21474836.47,...,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,0,376340.872457
12000,2023-03-20 06:13:58.123391,21474836.47,42.65,0.0,0.0,3230.97,3474.43,0.0,0.0,21474836.47,...,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,0,376381.941391
12001,2023-03-20 06:14:39.179122,21474836.47,42.65,0.0,0.0,3230.97,3474.43,0.0,0.0,21474836.47,...,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,0,376422.997122
12002,2023-03-20 06:15:20.245297,21474836.47,42.65,0.0,0.0,3230.97,3474.43,0.0,0.0,21474836.47,...,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,0,376464.063297

In [19]:
df_stop_101.Stopporsak.unique()

array(['Mekaniskt fel', 'Reparatör på plats'], dtype=object)

In [21]:
# Define the list of strings of interest
string_list = df_sensor_stop101.Stopporsak.unique().tolist()
string_list = [x for x in string_list if x != 'nan']

# Convert 'Stopporsak' column to string data type and replace NaN values with empty string
df_sensor_stop101['Stopporsak'] = df_sensor_stop101['Stopporsak'].apply(lambda x: str(x)).fillna('')

# Create a new column to store the RUL values
df_sensor_stop101['RUL'] = 0
# Loop through each row in the dataframe
for i, row in df_sensor_stop101.iterrows():
    
    # Check if any of the strings are present in the current row
    if any(s in row['Stopporsak'] for s in string_list):
        df_sensor_stop101.at[i, 'RUL'] = 0  # Set RUL to 0
        
    else:
        next_rows = df_sensor_stop101.loc[i+1:, 'Stopporsak'].apply(lambda x: any(s in x for s in string_list))

        if any(next_rows):
            next_row = next_rows.values.argmax() + i + 1
            time_diff = df_sensor_stop101.loc[next_row, 'time'] - row['time']
            df_sensor_stop101.at[i, 'RUL'] = time_diff
        else:
            df_sensor_stop101.at[i, 'RUL'] = 0

In [24]:
string_list = df_sensor_stop102.Stopporsak.unique().tolist()
string_list = [x for x in string_list if x != 'nan']

# Convert 'Stopporsak' column to string data type and replace NaN values with empty string
df_sensor_stop102['Stopporsak'] = df_sensor_stop102['Stopporsak'].apply(lambda x: str(x)).fillna('')

# Create a new column to store the RUL values
df_sensor_stop102['RUL'] = 0
# Loop through each row in the dataframe
for i, row in df_sensor_stop102.iterrows():
    
    # Check if any of the strings are present in the current row
    if any(s in row['Stopporsak'] for s in string_list):
        df_sensor_stop102.at[i, 'RUL'] = 0  # Set RUL to 0
        
    else:
        next_rows = df_sensor_stop102.loc[i+1:, 'Stopporsak'].apply(lambda x: any(s in x for s in string_list))
        if any(next_rows):
            next_row = next_rows.values.argmax() + i + 1
            time_diff = df_sensor_stop102.loc[next_row, 'time'] - row['time']
            df_sensor_stop102.at[i, 'RUL'] = time_diff
        else:
            df_sensor_stop102.at[i, 'RUL'] = 0

In [27]:
string_list = df_sensor_stop103.Stopporsak.unique().tolist()
string_list = [x for x in string_list if x != 'nan']

# Convert 'Stopporsak' column to string data type and replace NaN values with empty string
df_sensor_stop103['Stopporsak'] = df_sensor_stop103['Stopporsak'].apply(lambda x: str(x)).fillna('')

# Create a new column to store the RUL values
df_sensor_stop103['RUL'] = 0
# Loop through each row in the dataframe
for i, row in df_sensor_stop103.iterrows():
    
    # Check if any of the strings are present in the current row
    if any(s in row['Stopporsak'] for s in string_list):
        df_sensor_stop103.at[i, 'RUL'] = 0  # Set RUL to 0
        
    else:
        next_rows = df_sensor_stop103.loc[i+1:, 'Stopporsak'].apply(lambda x: any(s in x for s in string_list))
        if any(next_rows):
            next_row = next_rows.values.argmax() + i + 1
            time_diff = df_sensor_stop103.loc[next_row, 'time'] - row['time']
            df_sensor_stop103.at[i, 'RUL'] = time_diff
        else:
            df_sensor_stop103.at[i, 'RUL'] = 0

In [32]:
df_sensor_stop101.RUL[23:90]

23    0 days 00:12:08.202000
24    0 days 00:12:08.202000
25    0 days 00:11:40.202000
26    0 days 00:11:40.202000
27    0 days 00:11:19.202000
               ...
85    0 days 00:00:21.202000
86    0 days 00:00:21.202000
87                         0
88    0 days 12:02:45.003000
89    0 days 12:02:45.003000
Name: RUL, Length: 67, dtype: object

In [30]:
df_sensor_stop102.RUL[23:90]

23           0 days 00:12:04
24           0 days 00:12:04
25           0 days 00:11:43
26           0 days 00:11:43
27           0 days 00:11:19
               ...
85           0 days 00:00:19
86           0 days 00:00:19
87                         0
88    0 days 07:01:31.077000
89    0 days 07:01:02.077000
Name: RUL, Length: 67, dtype: object

In [31]:
df_sensor_stop103.RUL[23:90]

23    0 days 00:47:33.917000
24    0 days 00:47:33.917000
25    0 days 00:47:12.917000
26    0 days 00:47:12.917000
27    0 days 00:46:48.917000
               ...
85    0 days 00:35:48.917000
86    0 days 00:35:48.917000
87    0 days 00:35:29.917000
88    0 days 00:35:29.917000
89    0 days 00:35:00.917000
Name: RUL, Length: 67, dtype: object